// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VCFFileImport.Data;

#nullable disable

namespace VCFFileImport.Migrations
{
    [DbContext(typeof(VcfContext))]
    partial class VcfContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VCFFileImport.Models.Database.ImportFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ImportFileId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArchiveFileName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("DateTimeAddedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImportFileName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ImportFileName");

                    b.ToTable("ImportFiles", "vcf");
                });

            modelBuilder.Entity("VCFFileImport.Models.Database.ImportFileVcfTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ImportFileVcfTransactionId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ImportFileId")
                        .HasColumnType("int");

                    b.Property<int>("VcfTransactionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ImportFileId");

                    b.HasIndex("VcfTransactionId");

                    b.ToTable("ImportFileVCFTransactions", "vcf");
                });

            modelBuilder.Entity("VCFFileImport.Models.Database.VcfTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("VcfTransactionId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AccountCloseDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("AccountNumberLastSix")
                        .HasColumnType("int");

                    b.Property<string>("AccountNumberMaskfirst10Digits")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("AccountOpenDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("BillingAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("CardholderTransactionApproval")
                        .HasColumnType("bit");

                    b.Property<string>("CommodityCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EmployeeID")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("LastCreditLimitChangeDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("MerchantCategoryCode")
                        .HasColumnType("int");

                    b.Property<DateTime>("PostingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PurchaseIdentification")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("StatusCode")
                        .HasColumnType("int");

                    b.Property<DateTime>("StatusDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SupplierCity")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SupplierName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SupplierState")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("SupplierZipCode")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TransactionReferenceNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("TransactionTypeCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyName");

                    b.HasIndex("EmployeeID");

                    b.HasIndex("PostingDate");

                    b.HasIndex("TransactionDate");

                    b.HasIndex("TransactionReferenceNumber");

                    b.HasIndex("LastName", "FirstName");

                    b.ToTable("VcfTransactions", "vcf");
                });

            modelBuilder.Entity("VCFFileImport.Models.Database.ImportFileVcfTransaction", b =>
                {
                    b.HasOne("VCFFileImport.Models.Database.ImportFile", "ImportFile")
                        .WithMany("ImportFileVcfTransactions")
                        .HasForeignKey("ImportFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VCFFileImport.Models.Database.VcfTransaction", "VcfTransaction")
                        .WithMany()
                        .HasForeignKey("VcfTransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImportFile");

                    b.Navigation("VcfTransaction");
                });

            modelBuilder.Entity("VCFFileImport.Models.Database.ImportFile", b =>
                {
                    b.Navigation("ImportFileVcfTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
